[package]
name = "DeepOrca"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = "3.2.0"
dfdx = { version = "0.11.0", features = ["numpy"] }
vampirc-uci = "0.11.1"
