#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>


typedef struct Prophet Prophet;

typedef struct ProphetBoard {
    uint64_t white;
    uint64_t black;
    uint64_t pawns;
    uint64_t knights;
    uint64_t bishops;
    uint64_t rooks;
    uint64_t queens;
    uint64_t kings;
    uint8_t side_to_move;
} ProphetBoard;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

int32_t ProphetSingEvaluation(const struct Prophet *prophet, const struct ProphetBoard *board);

/**
 * Raise the Prophet. The Prophet shall not be freed.
 */
struct Prophet *RaiseProphet(const char *net_path);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus
